1、创建数组

In [1]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)
b = np.array(range(10))
c = np.array([i ** 2 for i in range(10)])  # 0到 9平方数组
print(b)
print(c)
d = np.array([i for i in range(10) if i%2 == 0])  # 0到 9偶数数组
print(d)
e = np.array([1.1,2.2,3.3,4.4,5.5],dtype=int)  # 指定类型为整数
print(f"e的结果是{e}")

[1 2 3 4 5]
[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]
[0 2 4 6 8]
e的结果是[1 2 3 4 5]
